export const Book_Categories = [
    { id: 1, value: 'generalia', name: 'Generalia' },
    { id: 2, value: 'biography', name: 'Biography' },
    { id: 3, value: 'library-science', name: 'Library Science' },
    { id: 4, value: 'journalism', name: 'Journalism' },
    { id: 5, value: 'natural-science', name: 'Natural Science' },
    { id: 6, value: 'mathematics', name: 'Mathematics' },
    { id: 7, value: 'physics', name: 'Physics' },
    { id: 8, value: 'engineering', name: 'Engineering' },
    { id: 9, value: 'chemistry', name: 'Chemistry' },
    { id: 10, value: 'technology', name: 'Technology' },
    { id: 11, value: 'biology', name: 'Biology' },
    { id: 12, value: 'geology', name: 'Geology' },
    { id: 13, value: 'botany', name: 'Botany' },
    { id: 14, value: 'agriculture', name: 'Agriculture' },
    { id: 15, value: 'zoology', name: 'Zoology' },
    { id: 16, value: 'medicine', name: 'Medicine' },
    { id: 17, value: 'useful-arts', name: 'Useful Arts' },
    { id: 18, value: 'mysticism', name: 'Mysticism' },
    { id: 19, value: 'fine-arts', name: 'Fine Arts' },
    { id: 20, value: 'literature', name: 'Literature' },
    { id: 21, value: 'tamil-literature', name: 'Tamil Literature' },
    { id: 22, value: 'english-literature', name: 'English Literature' },
    { id: 23, value: 'linguistics', name: 'Linguistics' },
    { id: 24, value: 'religion', name: 'Religion' },
    { id: 25, value: 'philosophy', name: 'Philosophy' },
    { id: 26, value: 'psychology', name: 'Psychology' },
    { id: 27, value: 'education', name: 'Education' },
    { id: 28, value: 'geography', name: 'Geography' },
    { id: 29, value: 'history', name: 'History' },
    { id: 30, value: 'political-science', name: 'Political Science' },
    { id: 31, value: 'economics', name: 'Economics' },
    { id: 32, value: 'sociology', name: 'Sociology' },
    { id: 33, value: 'law', name: 'Law' },
    { id: 34, value: 'tamil-poem', name: 'Tamil Poem' },
    { id: 35, value: 'tamil-drama', name: 'Tamil Drama' },
    { id: 36, value: 'tamil-fiction', name: 'Tamil Fiction' },
    { id: 37, value: 'tamil-letter', name: 'Tamil Letter' },
    { id: 38, value: 'tamil-speech', name: 'Tamil Speech' },
    { id: 39, value: 'tamil-essay', name: 'Tamil Essay' }
  ];